name: Run Tests
on: [push]

jobs:
  testing:
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']
        rails-version: [4.2.x, 5.0.x, 5.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gems
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}
        run: |
          bundle exec rspec
